# Generated by Django 4.2.5 on 2023-10-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
